### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by ChaunceyQ** [qinzheng93/GeoTransformer#17]
Hello, sir. The question is about creating the code runtime environment.
After reinstalling CUDA and downloading torch, I executed 'python setup.py build develop' and it still report the error, 'RuntimeError: Error compiling objects for extension'.

> Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    setup(
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py", line 643, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "F:\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Is this because I use win10? Or other issues caused the error?

**Comment by WuHaoYu21** [comment]
Linux can colve your problem.
Beacuse there have some cpp files need to be run in python,so you need some tools to make these cpp files convert to python.

**Comment by ChaunceyQ** [comment]
> Linux can colve your problem. Beacuse there have some cpp files need to be run in python,so you need some tools to make these cpp files convert to python.

Is it because WIN10 cannot use GCC ?

**Comment by WuHaoYu21** [comment]
If you want to run this file, you need to install C++ extension first, in Win10.
I had the same problem, but i couldn't find a suitable C++ extension to slove this problem.
So i give up , i choose to use Linux, because it's a easier solution.

**Comment by Dlemand** [comment]
> If you want to run this file, you need to install C++ extension first, in Win10. I had the same problem, but i couldn't find a suitable C++ extension to slove this problem. So i give up , i choose to use Linux, because it's a easier solution.

Hello,I have the same error in  ubuntu18.04. Could u please tell me that if the ununtu18.04 need a C++ extension ? Thanks a  lot.

**Comment by frankmaschine** [comment]
To build with win10 install: ninja & gcc (mingw..)

any file in  ..\GeoTransformer\geotransformer\extensions\cpu\
-> change any long to long long

replace size_t in grid_subsampling.cpp:
->  std::int64_t batch_size = lengths.size(0);
->  std::int64_t total_s_points = vec_s_points.size();

replace size_t in radius_neighbour.cpp:
->    std::int64_t total_q_points = q_points.size(0);
->    std::int64_t max_neighbors = vec_neighbor_indices.size() / total_q_points;

to run the demo.py:
in superpoint_target.py insert:
sel_indices = torch.from_numpy(sel_indices).cuda()
-> sel_indices = sel_indices.type(torch.LongTensor)
gt_corr_indices = gt_corr_indices[sel_indices]

**Comment by chalth** [comment]
I built it in Ubuntu18.04, but I have the same error. Do you know the solution?
