### ISSUE TITLE
No module named 'geotransformer.ext'`?

### ISSUE THREAD

**Issue by superstrong123** [qinzheng93/GeoTransformer#33]
### I tried to run test.py of 3Dmatch, but there is something wrong. Where is the file geotransformer.ext?
**CUDA_VISIBLE_DEVICES=0 python test.py --snapshot=~ -benchmark=3DMatch**
`Traceback (most recent call last):
  File "test.py", line 17, in <module>
    from dataset import test_data_loader
  File "/workspace/3dBuild_workspace/GeoTransformer/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/dataset.py", line 2, in <module>
    from geotransformer.utils.data import (
  File "/workspace/3dBuild_workspace/GeoTransformer/geotransformer/utils/data.py", line 6, in <module>
    from geotransformer.modules.ops import grid_subsample, radius_search
  File "/workspace/3dBuild_workspace/GeoTransformer/geotransformer/modules/ops/__init__.py", line 1, in <module>
    from geotransformer.modules.ops.grid_subsample import grid_subsample
  File "/workspace/3dBuild_workspace/GeoTransformer/geotransformer/modules/ops/grid_subsample.py", line 4, in <module>
    ext_module = importlib.import_module('geotransformer.ext')
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'geotransformer.ext'`

**Comment by PengboLi1998** [comment]
How to deal?

**Comment by superstrong123** [comment]
> How to deal?
you need build it in " setup.py "
