### ISSUE TITLE
Distributed error

### ISSUE THREAD

**Issue by chalth** [qinzheng93/GeoTransformer#38]
Hi, when i use  the distributed mode with running  
 CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 3 trainval.py, 
the error below occurred. Do you know the reason?

[2022-09-23 09:28:23] [INFO] Reducer buckets have been rebuilt in this iteration.
INFO - 2022-09-23 09:28:23,700 - distributed - Reducer buckets have been rebuilt in this iteration.
INFO - 2022-09-23 09:28:23,711 - distributed - Reducer buckets have been rebuilt in this iteration.
[2022-09-23 09:28:26] [INFO] Epoch: 1/40, iter: 10/6881, loss: 3.024, c_loss: 1.173, f_loss: 1.851, P00, RMSE: 0.860, RR: 0.400, lr: 3.000e-04, time: 0.264s/0.332s
[2022-09-23 09:28:30] [INFO] Epoch: 1/40, iter: 20/6881, loss: 2.895, c_loss: 1.022, f_loss: 1.873, P34, RMSE: 0.926, RR: 0.467, lr: 3.000e-04, time: 0.169s/0.328s
[2022-09-23 09:28:34] [INFO] Epoch: 1/40, iter: 30/6881, loss: 2.865, c_loss: 1.013, f_loss: 1.852, PIR: 0.005, IR: 0.485, RRE: 48.896, RTE: 1.069, RMSE: 0.742, RR: 0.533, lr: 3.000e-04, time: 0.142s/0.325s
[2022-09-23 09:28:38] [INFO] Epoch: 1/40, iter: 40/6881, loss: 2.873, c_loss: 1.011, f_loss: 1.863, PIR: 0.019, IR: 0.485, RRE: 28.251, RTE: 0.749, RMSE: 0.405, RR: 0.633, lr: 3.000e-04, time: 0.128s/0.326s
Traceback (most recent call last):
  File "trainval.py", line 62, in <module>
    main()
  File "trainval.py", line 58, in main
    trainer.run()
  File "/home/ubuntu/chenhong/GeoTransformer-main/geotransformer/engine/epoch_based_trainer.py", line 180, in run
    self.train_epoch()
  File "/home/ubuntu/chenhong/GeoTransformer-main/geotransformer/engine/epoch_based_trainer.py", line 95, in train_epoch
    output_dict, result_dict = self.train_step(self.epoch, self.inner_iteration, data_dict)
  File "trainval.py", line 41, in train_step
    output_dict = self.model(data_dict)
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/chenhong/GeoTransformer-main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/model.py", line 135, in forward
    ref_feats_c, src_feats_c = self.transformer(
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/chenhong/GeoTransformer-main/geotransformer/modules/geotransformer/geotransformer.py", line 143, in forward
    ref_feats, src_feats = self.transformer(
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/chenhong/GeoTransformer-main/geotransformer/modules/transformer/conditional_transformer.py", line 102, in forward
    feats1, scores1 = self.layers[i](feats1, feats1, embeddings1, memory_masks=masks1)
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/chenhong/GeoTransformer-main/geotransformer/modules/transformer/rpe_transformer.py", line 122, in forward
    hidden_states, attention_scores = self.attention(
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/chenhong/GeoTransformer-main/geotransformer/modules/transformer/rpe_transformer.py", line 92, in forward
    hidden_states, attention_scores = self.attention(
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/chenhong/GeoTransformer-main/geotransformer/modules/transformer/rpe_transformer.py", line 56, in forward
    attention_scores_p = torch.einsum('bhnc,bhnmc->bhnm', q, p)
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: CUDA out of memory. Tried to allocate 368.00 MiB (GPU 0; 10.76 GiB total capacity; 7.81 GiB already allocated; 366.81 MiB free; 9.23 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ubuntu/chenhong/.conda/envs/geotransformer/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/ubuntu/chenhong/.conda/envs/geotransformer/bin/python', '-u', 'trainval.py', '--local_rank=2']' returned non-zero exit status 1.

**Comment by jinhong-ni** [comment]
Your GPUs are out of memory.

**Comment by qinzheng93** [comment]
Make sure you have at least 24GB memory on GPU for training.
