### ISSUE TITLE
How to continue training

### ISSUE THREAD

**Issue by ShuaikangXie** [qinzheng93/GeoTransformer#50]
Hello, the author. I had a break when training the model. How can I continue to train according to the last training schedule?

**Comment by qinzheng93** [comment]
Use "--resume".

**Comment by ShuaikangXie** [comment]
When I run -- resume, the following error occurs: torch. nn. modules. module ModuleAttributeError: 'GeoTransformer' object has no attribute 'model_ dict'.Sincerely hope you can give me some advice.

**Comment by qinzheng93** [comment]
Can you post the complete tracing information?

**Comment by ShuaikangXie** [comment]
[2022-11-25 15:50:04] [INFO] Loading from "/home/lab/ally/GeoTransformer/GeoTransformer-main/output/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/snapshots/snapshot.pth.tar".
Traceback (most recent call last):
  File "trainval.py", line 62, in <module>
    main()
  File "trainval.py", line 58, in main
    trainer.run()
  File "/home/lab/xsk/geotransformer/GeoTransformer/geotransformer/engine/epoch_based_trainer.py", line 173, in run
    self.load_snapshot(osp.join(self.snapshot_dir, 'snapshot.pth.tar'))
  File "/home/lab/xsk/geotransformer/GeoTransformer/geotransformer/engine/base_trainer.py", line 151, in load_snapshot
    model_keys = set(self.model.model_dict().keys())
  File "/home/lab/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'GeoTransformer' object has no attribute 'model_dict'

**Comment by qinzheng93** [comment]
Fixed in the latest commit. You can change `model_dict()`  to `state_dict()` in line 151 of `GeoTransformer/geotransformer/engine/base_trainer.py`

**Comment by ShuaikangXie** [comment]
According to your method, I have successfully started the code. Thank you for your reply.

**Comment by qinzheng93** [comment]
You are welcome.
