### ISSUE TITLE
selected index k out of range

### ISSUE THREAD

**Issue by desaibhargav** [qinzheng93/GeoTransformer#59]
Thank you for open sourcing this amazing work ❤️

I tried to follow the installation instructions and run it for my data using demo.py. However, I'm met with a RuntimeError of "selected index k out of range" 

I'm able to load the model, so this likely comes from the forward pass (probably the SuperPoint estimation step). 

I'm using the default configuration for KPConv and GeoTransformer and my point clouds are in the range of 10K points to 30K points (post downsampling). I could share the links to my files if that helps. 

Best,
Bhargav

**Comment by qinzheng93** [comment]
How large area does the point cloud cover?

**Comment by hiyyg** [comment]
Hi, I got the same error. How did you resolve it? @desaibhargav @qinzheng93

**Comment by W-QY** [comment]
> Hi, I got the same error. How did you resolve it? @desaibhargav @qinzheng93

I also encountered the same problem, have you solved it?

**Comment by mikelig** [comment]
Hello, I am having the same error while testing my data of 20-28k points. 

From other issues I have read that one solution could be to create a new dataset.py of my data, but I don't totally understand this approach.

Did you solve the problem? And if so, could you please provide some details about it? @qinzheng93 @desaibhargav 
 @hiyyg @W-QY 

Thank you

**Comment by andy4120** [comment]
same questions here , python experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/demo.py  --src_file "" --ref_file  ""  --gt_file   ""    --weights  geotransformer-3dmatch.pth.tar 
(930, 3) (8973, 3) (930, 1) (8973, 1)
Traceback (most recent call last):
  File "experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/demo.py", line 127, in <module>
    main()
  File "experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/demo.py", line 100, in main
    output_dict = model(data_dict)
  File "/media/nv/其他/anaconda3/envs/yolo5torch118/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/47/Project_andy/Project/Open3D/GeoTransformer-main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/model.py", line 102, in forward
    src_points_f, src_points_c, self.num_points_in_patch
  File "/media/nv/其他/anaconda3/envs/yolo5torch118/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/media/47/Project_andy/Project/Open3D/GeoTransformer-main/geotransformer/modules/ops/pointcloud_partition.py", line 95, in point_to_node_partition
    node_knn_indices = sq_dist_mat.topk(k=point_limit, dim=1, largest=False)[1]  # (M, K)
RuntimeError: invalid argument 5: k not in range for dimension at /opt/conda/conda-bld/pytorch_1607370141920/work/aten/src/THC/generic/THCTensorTopK.cu:26 ,what may cause this problem ,the classes of dataset ? 
 ,Do I have to create custom dataset ? 


`




def load_data(args):
    voxel_size=0.01
    pcd_file_path_src='mesh_menya.pcd'
    pcd_src = o3d.io.read_point_cloud(pcd_file_path_src)  
    pcd_src = pcd_src.voxel_down_sample(voxel_size)  
    pcd_file_path_target='mesh_whole.pcd'
    pcd_target = o3d.io.read_point_cloud(pcd_file_path_target)  
    pcd_target = pcd_target.voxel_down_sample(voxel_size)      

    # src_points = np.load(args.src_file)
    # ref_points = np.load(args.ref_file)
    src_points = np.array(pcd_src.points)
    ref_points =np.array( pcd_target.points ) 
    import pdb
    #pdb.set_trace()
    src_feats = np.ones_like(src_points[:, :1])
    ref_feats = np.ones_like(ref_points[:, :1])
    print(src_points.shape,ref_points.shape,src_feats.shape,ref_feats.shape,)

    data_dict = {
        "ref_points": ref_points.astype(np.float32),
        "src_points": src_points.astype(np.float32),
        "ref_feats": ref_feats.astype(np.float32),
        "src_feats": src_feats.astype(np.float32),
    }
    data_dict["transform"] = np.eye(4, dtype=np.float32)
    if(0):
        if args.gt_file is not None:
            transform = np.load(args.gt_file)
            data_dict["transform"] = transform.astype(np.float32)

    return data_dict
 


def main():
    parser = make_parser()
    args = parser.parse_args()

    cfg = make_cfg()

    # prepare data
    data_dict = load_data(args)
    neighbor_limits = [38, 36, 36, 38]  # default setting in 3DMatch
    neighbor_limits = [8,8,8,8]  
    data_dict = registration_collate_fn_stack_mode(
        [data_dict], cfg.backbone.num_stages, cfg.backbone.init_voxel_size, cfg.backbone.init_radius, neighbor_limits
    )

    # prepare model
    model = create_model(cfg).cuda()
    state_dict = torch.load(args.weights)
    model.load_state_dict(state_dict["model"])

    # prediction
    data_dict = to_cuda(data_dict)
    output_dict = model(data_dict)
    data_dict = release_cuda(data_dict)
    output_dict = release_cuda(output_dict)
`

**Comment by andy4120** [comment]
solved my problem ,by changing the cfg voxsize

**Comment by CossellCollege** [comment]
> solved my problem ,by changing the cfg voxsize

Hello，the same error occurs. I want to know what size of your origin pointcloud, my pointcloud's xyz are in 0-40cm. I tried to make the size to 2.5cm, but nothing to change. It confuses me a lot, looking forward to your help！

**Comment by wangluo666** [comment]
@desaibhargav  @hiyyg  @W-QY  @mikelig 

I have solved it. Try it:


@torch.no_grad()
def point_to_node_partition(
    points: torch.Tensor,
    nodes: torch.Tensor,
    point_limit: int,
    return_count: bool = False,
):
    r"""Point-to-Node partition to the point cloud.

    Fixed knn bug.

    Args:
        points (Tensor): (N, 3)
        nodes (Tensor): (M, 3)
        point_limit (int): max number of points to each node
        return_count (bool=False): whether to return `node_sizes`

    Returns:
        point_to_node (Tensor): (N,)
        node_sizes (LongTensor): (M,)
        node_masks (BoolTensor): (M,)
        node_knn_indices (LongTensor): (M, K)
        node_knn_masks (BoolTensor) (M, K)
    """
    sq_dist_mat = pairwise_distance(nodes, points)  # (M, N)

    point_to_node = sq_dist_mat.min(dim=0)[1]  # (N,)
    node_masks = torch.zeros(nodes.shape[0], dtype=torch.bool).cuda()  # (M,)
    node_masks.index_fill_(0, point_to_node, True)

    matching_masks = torch.zeros_like(sq_dist_mat, dtype=torch.bool)  # (M, N)
    point_indices = torch.arange(points.shape[0]).cuda()  # (N,)
    matching_masks[point_to_node, point_indices] = True  # (M, N)
    sq_dist_mat.masked_fill_(~matching_masks, 1e12)  # (M, N)

    if point_limit > sq_dist_mat.shape[1]:
        sq_dist_mat = sq_dist_mat.repeat(1, math.ceil(point_limit / points.shape[0]))
    node_knn_indices = sq_dist_mat.topk(k=point_limit, dim=1, largest=False)[1]  # (M, K)
    node_knn_masks = node_knn_indices < points.shape[0]
    node_knn_indices = node_knn_indices % points.shape[0]
    node_knn_node_indices = index_select(point_to_node, node_knn_indices, dim=0)  # (M, K)
    node_indices = torch.arange(nodes.shape[0]).cuda().unsqueeze(1).expand(-1, point_limit)  # (M, K)
    node_knn_masks = node_knn_masks & torch.eq(node_knn_node_indices, node_indices)  # (M, K)
    node_knn_indices.masked_fill_(~node_knn_masks, points.shape[0])

    if return_count:
        unique_indices, unique_counts = torch.unique(point_to_node, return_counts=True)
        node_sizes = torch.zeros(nodes.shape[0], dtype=torch.long).cuda()  # (M,)
        node_sizes.index_put_([unique_indices], unique_counts)
        return point_to_node, node_sizes, node_masks, node_knn_indices, node_knn_masks
    else:
        return point_to_node, node_masks, node_knn_indices, node_knn_masks

**Comment by wangluo666** [comment]
In addtion, you may also need to fix GeoTransformer/geotransformer/modules/geotransformer/geotransformer.py into


class GeometricStructureEmbedding(nn.Module):
    ...
    def get_embedding_indices(self, points):
        ...(line 41)
        k = self.angle_k
        if self.angle_k + 1 > num_point:
            repeat_factor = math.ceil((self.angle_k + 1) / num_point)
            dist_map = dist_map.repeat(1, 1, repeat_factor)  # (B, N, N * repeat_factor)
        knn_indices = dist_map.topk(k=k + 1, dim=2, largest=False)[1][:, :, 1:]  # (B, N, k)
        valid_mask = knn_indices < num_point  # 标记有效索引
        knn_indices = knn_indices % num_point  # 将索引映射回合法范围 (B, N, k)
        knn_indices = knn_indices.unsqueeze(3).expand(batch_size, num_point, k, 3)  # (B, N, k, 3)
       ...
