### ISSUE TITLE
_pickle.UnpicklingError in running test.py

### ISSUE THREAD

**Issue by kuixu** [qinzheng93/GeoTransformer#7]
Hi, Zheng! This is great work on point registration! I am deploying the code on the local machine. While I get an error when running with the command `python test.py --test_iter=5 --snapshot=../../weights/geotransformer-kitti.pth.tar`. Could you help me to solve this problem? Thanks.

```
[2022-04-05 15:48:53] [INFO] Loading from "../../weights/geotransformer-kitti.pth.tar".
Traceback (most recent call last):
  File "test.py", line 94, in <module>
    main()
  File "test.py", line 90, in main
    tester.run()
  File "exp/GeoTransformer/geotransformer/engine/single_tester.py", line 41, in run
    self.load_snapshot(self.args.snapshot)
  File "exp/GeoTransformer/geotransformer/engine/base_tester.py", line 67, in load_snapshot
    state_dict = torch.load(snapshot, map_location=torch.device('cpu'))
  File "miniconda3/envs/geotransformer/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "miniconda3/envs/geotransformer/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by kuixu** [comment]
Solved. 

It’s the problem of `git clone` does not pull the whole pre-trained model file.
