### ISSUE TITLE
When I train with my own data, I encounter an error: RuntimeError: shape '[1, 64, 256]' is invalid for input of size 0.

### ISSUE THREAD

**Issue by FDC-WuWeb** [qinzheng93/GeoTransformer#83]
Thank you for sharing the code. When I train with my own dataset, the program throws an error. I hope to receive your response as well. If anyone else who has encountered this issue sees this question, please feel free to share a solution. Your help would be greatly appreciated.
Traceback (most recent call last):
  File "/data/Wuweb/PointCloud/code/GeoORG/GeoTransformer-main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/trainval.py", line 63, in <module>
    main()
  File "/data/Wuweb/PointCloud/code/GeoORG/GeoTransformer-main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/trainval.py", line 59, in main
    trainer.run()
  File "/data/Wuweb/PointCloud/code/GeoORG/GeoTransformer-main/geotransformer/engine/epoch_based_trainer.py", line 180, in run
    self.train_epoch()
  File "/data/Wuweb/PointCloud/code/GeoORG/GeoTransformer-main/geotransformer/engine/epoch_based_trainer.py", line 95, in train_epoch
    output_dict, result_dict = self.train_step(self.epoch, self.inner_iteration, data_dict)
  File "/data/Wuweb/PointCloud/code/GeoORG/GeoTransformer-main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/trainval.py", line 42, in train_step
    output_dict = self.model(data_dict)
  File "/home/Wuweb/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/Wuweb/PointCloud/code/GeoORG/GeoTransformer-main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/model.py", line 187, in forward
    matching_scores = torch.einsum('bnd,bmd->bnm', ref_node_corr_knn_feats, src_node_corr_knn_feats)  # (P, K, K)
  File "/home/Wuweb/anaconda3/envs/geotransformer/lib/python3.8/site-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: shape '[1, 64, 256]' is invalid for input of size 0

**Comment by WundtAsim** [comment]
hello, I have the same question, have you ever solved this problem?

**Comment by FDC-WuWeb** [comment]
> hello, I have the same question, have you ever solved this problem?

I remember it seems like the gold standard of my dataset got mixed up, and the two point clouds didn't match correctly after the transformation.

**Comment by maSiki29** [comment]
Hi, I have the same problem, I've noticed that this issue happens when generating ground-truth superpoint/patch correspondences at line 110 in the file [model.py](https://github.com/qinzheng93/GeoTransformer/blob/main/experiments/geotransformer.3dmatch.stage4.gse.k3.max.oacl.stage2.sinkhorn/model.py).
Could someone please provide me with guidance on how to solve this issue? Thanks!
