### ISSUE TITLE
building 'geotransformer.ext' extension :RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by ZhangjLiang** [qinzheng93/GeoTransformer#89]
hello! when I try to bulid 'geotransformer.ext' I meet a problem

E:\1Code\GeoTransformer-main\geotransformer\extensions\cpu\grid_subsampling\grid_subsampling.cpp(46): error C2398: Ԫ�ء�1��: �ӡ�size_t��ת��Ϊ��_Ty����Ҫ����ת��
        with
        [
            _Ty=int64_t
        ]
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "E:\Anaconda3\envs\geotransformer\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\1Code\GeoTransformer-main\setup.py", line 5, in <module>
    setup(
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
    self.run_command(cmd_name)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\dist.py", line 989, in run_command
    super().run_command(command)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
    _build_ext.run(self)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\command\build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\Cython\Distutils\build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py", line 643, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "E:\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Process finished with exit code 1

seems something wong but I don't understand ,have you ever meet this promblem?

**Comment by solemotive** [comment]
Hello, have you solved the problem

**Comment by solemotive** [comment]
> 你好！当我尝试构建 'geotransformer.ext' 时，我遇到了一个问题
> 
> E：\1Code\GeoTransformer-main\geotransformer\extensions\cpu\grid_subsampling\grid_subsampling.cpp（46）：错误 C2398：错误 C2398：中文 1：中文size_t 中文 _Ty 中文 中文 与 [ _Ty=int64_t ] 忍者：构建停止：子命令失败。回溯（最近调用最后一次）：文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py”，第 1533 行，_run_ninja_build subprocess.run（ 文件“E：\Anaconda3\envs\geotransformer\lib\subprocess.py”，第 512 行，在运行中 raise CalledProcessError（retcode， process.args， subprocess.CalledProcessError：命令 '['ninja'， '-v']' 返回非零退出状态 1。
> 
> 上述异常是导致以下异常的直接原因：
> 
> 回溯（最近一次调用最后）：文件“E：\1Code\GeoTransformer-main\setup.py”，第 5 行，在 setup（ 文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools__init__.py”，第 103 行，在设置中返回 distutils.core.setup（**attrs）文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\core.py”，第 185 行，在设置中返回 run_commands（dist）文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\core.py”，第 201 行，run_commands dist.run_commands（） 文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\dist.py”，第 969 行，run_commands self.run_command（cmd） 文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\dist.py”，第 989 行，run_command super（）.run_command（命令）文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\dist.py”，第 988 行，run_command cmd_obj.run（） 文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\command\build.py”，第 131 行，运行self.run_command（cmd_name） 文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\cmd.py”，第 318 行，run_command self.distribution.run_command（command） 文件 “E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\dist.py”，第 989 行，run_command super（）.run_command（命令） 文件 “E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\dist.py”，第 988 行，run_command cmd_obj.run（） 文件 “E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools\command\build_ext.py”，第 88 行，运行 _build_ext.run（self） 文件 “E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\command\build_ext.py”，第 345 行，运行 self.build_extensions（） 文件 “E：\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py”，第 670 行，build_extensions build_ext.build_extensions（self）文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\command\build_ext.py”，第 467 行，build_extensions self._build_extensions_serial（） 文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\command\build_ext.py”，第 493 行，_build_extensions_serial self.build_extension（ext） 文件中build_ext.py“，第 249 行，build_extension _build_ext.build_extension（self， ext） 文件”E：\Anaconda3\envs\geotransformer\lib\site-packages\Cython\Distutils\build_ext.py“，第 135 行，build_extension super（build_ext， self）.build_extension（ext） 文件”E：\Anaconda3\envs\geotransformer\lib\site-packages\setuptools_distutils\command\build_ext.py“，第 548 行，build_extension对象 = self.compiler.compile（文件 “E：\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py”，第 643 行，win_wrap_ninja_compile_write_ninja_file_and_compile_objects（文件 “E：\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py”，第 1250 行，_write_ninja_file_and_compile_objects _run_ninja_build（ 文件“E：\Anaconda3\envs\geotransformer\lib\site-packages\torch\utils\cpp_extension.py”， 第 1555 行，_run_ninja_build 从 e 引发 RuntimeError（message） RuntimeError： Error compiling objects for extension
> 
> 进程已完成，退出代码为 1
> 
> 似乎有什么 wong 但我不明白，你有没有遇到过这种情况？

请问你解决了吗

**Comment by N0NEWHY** [comment]
Change the code  in `torch/utils/cpp_extension.py`:
['ninja','-v'] to ['ninja','--v'] or ['ninja','--version']

**Comment by pean1128** [comment]
https://blog.csdn.net/qq_46170379/article/details/138791937
